### ISSUE TITLE
need to stream this over tcp

### ISSUE THREAD

**Issue by rajeshkrarora1** [florian-asche/RaspberryPiStreamingCamera#1]
hi florian-asche, thanks for this wonderful project, i was wondering if we can stream this rtsp feed over tcp instead of udp

thanks and regards

rajesh kumar

**Comment by florian-asche** [comment]
Hi,

i use the server from here: https://github.com/mpromonet/v4l2rtspserver.

Startparameters can be changed in /etc/systemd/system/RTSP-Server.service

If i am correct, you need to change the -P to -p.
```
-P port  : RTSP port (default 8554)
-p port  : RTSP over HTTP port (default 0)
```
