### ISSUE TITLE
Preconfigured Image

### ISSUE THREAD

**Issue by electric-m** [florian-asche/RaspberryPiStreamingCamera#2]
Hey Florian,

it may seem dumb but I understood, that you provide a preconfigured image for the Raspberry Pi?
I cannot find where to download it for my Pi Zero W.

Can you help?

**Comment by florian-asche** [comment]
Hi,

you can download it here: https://github.com/florian-asche/RaspberryPiStreamingCamera/releases.

Regards, Florian
